//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.AI.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.AI.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Get Element 的本地化字符串。
        /// </summary>
        public static string activity_getelement {
            get {
                return ResourceManager.GetString("activity_getelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop activity 的本地化字符串。
        /// </summary>
        public static string activity_getelement_drop_hint {
            get {
                return ResourceManager.GetString("activity_getelement_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight 的本地化字符串。
        /// </summary>
        public static string activity_getelement_highlight {
            get {
                return ResourceManager.GetString("activity_getelement_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Selector 的本地化字符串。
        /// </summary>
        public static string activity_getelement_open_selector {
            get {
                return ResourceManager.GetString("activity_getelement_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find an Windows UI element based on selector 的本地化字符串。
        /// </summary>
        public static string activity_getelement_tooltip {
            get {
                return ResourceManager.GetString("activity_getelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get Text 的本地化字符串。
        /// </summary>
        public static string activity_gettext {
            get {
                return ResourceManager.GetString("activity_gettext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop activity 的本地化字符串。
        /// </summary>
        public static string activity_gettext_drop_hint {
            get {
                return ResourceManager.GetString("activity_gettext_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open URL 的本地化字符串。
        /// </summary>
        public static string activity_openurl {
            get {
                return ResourceManager.GetString("activity_openurl", resourceCulture);
            }
        }
        
		 /// <summary>
        ///   Looks up a localized string similar to Limit to.
        /// </summary>
        public static string activity_gettext_limit {
            get {
                return ResourceManager.GetString("activity_gettext_limit", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Looks up a localized string similar to Search only for this word.
        /// </summary>
        public static string activity_gettext_limit_hint {
            get {
                return ResourceManager.GetString("activity_gettext_limit_hint", resourceCulture);
            }
        }
		
		
		/// <summary>
        ///   Looks up a localized string similar to Using OCR get all text from a image, can be limited to a specific word or sentence.
        /// </summary>
        public static string activity_gettext_tooltip {
            get {
                return ResourceManager.GetString("activity_gettext_tooltip", resourceCulture);
            }
        }
		
        /// <summary>
        ///   查找类似 Get current 的本地化字符串。
        /// </summary>
        public static string activity_openurl_getcurrent {
            get {
                return ResourceManager.GetString("activity_openurl_getcurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open the specefied url in Internet Explorer 的本地化字符串。
        /// </summary>
        public static string activity_openurl_tooltip {
            get {
                return ResourceManager.GetString("activity_openurl_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for ready 的本地化字符串。
        /// </summary>
        public static string activity_waitforready {
            get {
                return ResourceManager.GetString("activity_waitforready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for page page to be ready / is not loading 的本地化字符串。
        /// </summary>
        public static string activity_waitforready_help {
            get {
                return ResourceManager.GetString("activity_waitforready_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Caching browser object 的本地化字符串。
        /// </summary>
        public static string enable_caching_browser {
            get {
                return ResourceManager.GetString("enable_caching_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save browser object, instead of searching for the window doing each call 的本地化字符串。
        /// </summary>
        public static string enable_caching_browser_help {
            get {
                return ResourceManager.GetString("enable_caching_browser_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable XPath 的本地化字符串。
        /// </summary>
        public static string enable_xpath_support {
            get {
                return ResourceManager.GetString("enable_xpath_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable experimental XPath support in IE 的本地化字符串。
        /// </summary>
        public static string enable_xpath_support_help {
            get {
                return ResourceManager.GetString("enable_xpath_support_help", resourceCulture);
            }
        }
    }
}
