//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenRPA.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenRPA.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add variables 的本地化字符串。
        /// </summary>
        public static string activity_add_variables {
            get {
                return ResourceManager.GetString("activity_add_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animate Mouse 的本地化字符串。
        /// </summary>
        public static string activity_animatemouse {
            get {
                return ResourceManager.GetString("activity_animatemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visibly move the mouse, instead of instantly moving it to the destination 的本地化字符串。
        /// </summary>
        public static string activity_animatemouse_help {
            get {
                return ResourceManager.GetString("activity_animatemouse_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Animate Move 的本地化字符串。
        /// </summary>
        public static string activity_animatemove {
            get {
                return ResourceManager.GetString("activity_animatemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visibly move the window, instead of instantly moving it to the destination 的本地化字符串。
        /// </summary>
        public static string activity_animatemove_help {
            get {
                return ResourceManager.GetString("activity_animatemove_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blocking 的本地化字符串。
        /// </summary>
        public static string activity_blocking {
            get {
                return ResourceManager.GetString("activity_blocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Block execution until the complete 的本地化字符串。
        /// </summary>
        public static string activity_blocking_help {
            get {
                return ResourceManager.GetString("activity_blocking_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Running 的本地化字符串。
        /// </summary>
        public static string activity_checkrunning {
            get {
                return ResourceManager.GetString("activity_checkrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check if application is already running using the selector, if set to false, will launch a new application no matter what 的本地化字符串。
        /// </summary>
        public static string activity_checkrunning_help {
            get {
                return ResourceManager.GetString("activity_checkrunning_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double-click to view 的本地化字符串。
        /// </summary>
        public static string activity_click_to_view {
            get {
                return ResourceManager.GetString("activity_click_to_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Delay 的本地化字符串。
        /// </summary>
        public static string activity_clickdelay {
            get {
                return ResourceManager.GetString("activity_clickdelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay between each keystroke 的本地化字符串。
        /// </summary>
        public static string activity_clickdelay_help {
            get {
                return ResourceManager.GetString("activity_clickdelay_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Element 的本地化字符串。
        /// </summary>
        public static string activity_clickelement {
            get {
                return ResourceManager.GetString("activity_clickelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on an element found with GetElement 的本地化字符串。
        /// </summary>
        public static string activity_clickelement_tooltip {
            get {
                return ResourceManager.GetString("activity_clickelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Application 的本地化字符串。
        /// </summary>
        public static string activity_closeapplication {
            get {
                return ResourceManager.GetString("activity_closeapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find application based on a UI selector and then closes the Application 的本地化字符串。
        /// </summary>
        public static string activity_closeapplication_tooltip {
            get {
                return ResourceManager.GetString("activity_closeapplication_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment Out 的本地化字符串。
        /// </summary>
        public static string activity_commentout {
            get {
                return ResourceManager.GetString("activity_commentout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore everything inside this Acitvity, handy for quickly remarking something out 的本地化字符串。
        /// </summary>
        public static string activity_commentout_tooltip {
            get {
                return ResourceManager.GetString("activity_commentout_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Clipboard 的本地化字符串。
        /// </summary>
        public static string activity_copyclipboard {
            get {
                return ResourceManager.GetString("activity_copyclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy content of Clipboard into a variable 的本地化字符串。
        /// </summary>
        public static string activity_copyclipboard_tooltip {
            get {
                return ResourceManager.GetString("activity_copyclipboard_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Table 的本地化字符串。
        /// </summary>
        public static string activity_datatable {
            get {
                return ResourceManager.GetString("activity_datatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DataTable to work with 的本地化字符串。
        /// </summary>
        public static string activity_datatable_help {
            get {
                return ResourceManager.GetString("activity_datatable_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data View 的本地化字符串。
        /// </summary>
        public static string activity_dataview {
            get {
                return ResourceManager.GetString("activity_dataview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The DateView to work with 的本地化字符串。
        /// </summary>
        public static string activity_dataview_help {
            get {
                return ResourceManager.GetString("activity_dataview_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detector 的本地化字符串。
        /// </summary>
        public static string activity_detector {
            get {
                return ResourceManager.GetString("activity_detector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will wait for this detector to trigger, then the workflow will continue 的本地化字符串。
        /// </summary>
        public static string activity_detector_help {
            get {
                return ResourceManager.GetString("activity_detector_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Puts workflow in idle mode, waiting on selected detector to trigger 的本地化字符串。
        /// </summary>
        public static string activity_detector_tooltip {
            get {
                return ResourceManager.GetString("activity_detector_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displayname 的本地化字符串。
        /// </summary>
        public static string activity_displayname {
            get {
                return ResourceManager.GetString("activity_displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Displayname inside the workflow designer 的本地化字符串。
        /// </summary>
        public static string activity_displayname_help {
            get {
                return ResourceManager.GetString("activity_displayname_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Double Click 的本地化字符串。
        /// </summary>
        public static string activity_doubleclick {
            get {
                return ResourceManager.GetString("activity_doubleclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do a double click instead of single click 的本地化字符串。
        /// </summary>
        public static string activity_doubleclick_help {
            get {
                return ResourceManager.GetString("activity_doubleclick_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop activity 的本地化字符串。
        /// </summary>
        public static string activity_drop_hint {
            get {
                return ResourceManager.GetString("activity_drop_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration 的本地化字符串。
        /// </summary>
        public static string activity_duration {
            get {
                return ResourceManager.GetString("activity_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Will run for the duration 的本地化字符串。
        /// </summary>
        public static string activity_duration_help {
            get {
                return ResourceManager.GetString("activity_duration_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Element 的本地化字符串。
        /// </summary>
        public static string activity_element {
            get {
                return ResourceManager.GetString("activity_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click on this element, the return type of all GetElement activites and some others 的本地化字符串。
        /// </summary>
        public static string activity_element_help {
            get {
                return ResourceManager.GetString("activity_element_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Focus Element 的本地化字符串。
        /// </summary>
        public static string activity_focuselement {
            get {
                return ResourceManager.GetString("activity_focuselement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Give element focus 的本地化字符串。
        /// </summary>
        public static string activity_focuselement_tooltip {
            get {
                return ResourceManager.GetString("activity_focuselement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force 的本地化字符串。
        /// </summary>
        public static string activity_force {
            get {
                return ResourceManager.GetString("activity_force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forcefully do the action 的本地化字符串。
        /// </summary>
        public static string activity_force_help {
            get {
                return ResourceManager.GetString("activity_force_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foreach DataRow 的本地化字符串。
        /// </summary>
        public static string activity_foreachdatarow {
            get {
                return ResourceManager.GetString("activity_foreachdatarow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enumerate through each row inside a DataTable 的本地化字符串。
        /// </summary>
        public static string activity_foreachdatarow_tooltip {
            get {
                return ResourceManager.GetString("activity_foreachdatarow_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        public static string activity_height {
            get {
                return ResourceManager.GetString("activity_height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If set, will move the window to this location 的本地化字符串。
        /// </summary>
        public static string activity_height_help {
            get {
                return ResourceManager.GetString("activity_height_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight 的本地化字符串。
        /// </summary>
        public static string activity_highlight {
            get {
                return ResourceManager.GetString("activity_highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight Element 的本地化字符串。
        /// </summary>
        public static string activity_highlightelement {
            get {
                return ResourceManager.GetString("activity_highlightelement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight an element found with GetElement 的本地化字符串。
        /// </summary>
        public static string activity_highlightelement_tooltip {
            get {
                return ResourceManager.GetString("activity_highlightelement_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore Errors 的本地化字符串。
        /// </summary>
        public static string activity_ignoreerrors {
            get {
                return ResourceManager.GetString("activity_ignoreerrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If an error occurs, will ignore it an continue 的本地化字符串。
        /// </summary>
        public static string activity_ignoreerrors_help {
            get {
                return ResourceManager.GetString("activity_ignoreerrors_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Result 的本地化字符串。
        /// </summary>
        public static string activity_imageresult {
            get {
                return ResourceManager.GetString("activity_imageresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return the result as an image 的本地化字符串。
        /// </summary>
        public static string activity_imageresult_help {
            get {
                return ResourceManager.GetString("activity_imageresult_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Clipboard 的本地化字符串。
        /// </summary>
        public static string activity_insertclipboard {
            get {
                return ResourceManager.GetString("activity_insertclipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert new content into the users Clipboard buffer 的本地化字符串。
        /// </summary>
        public static string activity_insertclipboard_tooltip {
            get {
                return ResourceManager.GetString("activity_insertclipboard_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke OpenFlow 的本地化字符串。
        /// </summary>
        public static string activity_invokeopenflow {
            get {
                return ResourceManager.GetString("activity_invokeopenflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke a workflow in node registered for RPA usage inside OpenFlow 的本地化字符串。
        /// </summary>
        public static string activity_invokeopenflow_tooltip {
            get {
                return ResourceManager.GetString("activity_invokeopenflow_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke OpenRPA 的本地化字符串。
        /// </summary>
        public static string activity_invokeopenrpa {
            get {
                return ResourceManager.GetString("activity_invokeopenrpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke a local OpenRPA Workflow 的本地化字符串。
        /// </summary>
        public static string activity_invokeopenrpa_tooltip {
            get {
                return ResourceManager.GetString("activity_invokeopenrpa_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke Remote OpenRPA 的本地化字符串。
        /// </summary>
        public static string activity_invokeremoteopenrpa {
            get {
                return ResourceManager.GetString("activity_invokeremoteopenrpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke a OpenRPA Workflow on a remote Robot 的本地化字符串。
        /// </summary>
        public static string activity_invokeremoteopenrpa_tooltip {
            get {
                return ResourceManager.GetString("activity_invokeremoteopenrpa_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key Modifiers 的本地化字符串。
        /// </summary>
        public static string activity_keymodifiers {
            get {
                return ResourceManager.GetString("activity_keymodifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold this key down, while clicking, only works if Virtual click is disabled 的本地化字符串。
        /// </summary>
        public static string activity_keymodifiers_help {
            get {
                return ResourceManager.GetString("activity_keymodifiers_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Map Variables 的本地化字符串。
        /// </summary>
        public static string activity_map_variables {
            get {
                return ResourceManager.GetString("activity_map_variables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse Button 的本地化字符串。
        /// </summary>
        public static string activity_mousebutton {
            get {
                return ResourceManager.GetString("activity_mousebutton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouse button to click with 的本地化字符串。
        /// </summary>
        public static string activity_mousebutton_help {
            get {
                return ResourceManager.GetString("activity_mousebutton_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Mouse 的本地化字符串。
        /// </summary>
        public static string activity_movemouse {
            get {
                return ResourceManager.GetString("activity_movemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move mouse cursor to a location relative to an element found with GetElement (or desktop if no element supplied) 的本地化字符串。
        /// </summary>
        public static string activity_movemouse_tooltip {
            get {
                return ResourceManager.GetString("activity_movemouse_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 message box 的本地化字符串。
        /// </summary>
        public static string activity_msgbox_text
        {
            get {
                return ResourceManager.GetString("activity_msgbox_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X Offset 的本地化字符串。
        /// </summary>
        public static string activity_offsetx {
            get {
                return ResourceManager.GetString("activity_offsetx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click with this offset inside the element 的本地化字符串。
        /// </summary>
        public static string activity_offsetx_help {
            get {
                return ResourceManager.GetString("activity_offsetx_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y Offset 的本地化字符串。
        /// </summary>
        public static string activity_offsety {
            get {
                return ResourceManager.GetString("activity_offsety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click with this offset inside the element 的本地化字符串。
        /// </summary>
        public static string activity_offsety_help {
            get {
                return ResourceManager.GetString("activity_offsety_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Selector 的本地化字符串。
        /// </summary>
        public static string activity_open_selector {
            get {
                return ResourceManager.GetString("activity_open_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Application 的本地化字符串。
        /// </summary>
        public static string activity_openapplication {
            get {
                return ResourceManager.GetString("activity_openapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for Windows element based on a selector, and give it focus, if not found start the application 的本地化字符串。
        /// </summary>
        public static string activity_openapplication_tooltip {
            get {
                return ResourceManager.GetString("activity_openapplication_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post Wait 的本地化字符串。
        /// </summary>
        public static string activity_postwait {
            get {
                return ResourceManager.GetString("activity_postwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait this amount of time, after doing the click, help full one applications that can be very slow to react on clicks 的本地化字符串。
        /// </summary>
        public static string activity_postwait_help {
            get {
                return ResourceManager.GetString("activity_postwait_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        public static string activity_result {
            get {
                return ResourceManager.GetString("activity_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the result into this variable 的本地化字符串。
        /// </summary>
        public static string activity_result_help {
            get {
                return ResourceManager.GetString("activity_result_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Element 的本地化字符串。
        /// </summary>
        public static string activity_select_element {
            get {
                return ResourceManager.GetString("activity_select_element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector 的本地化字符串。
        /// </summary>
        public static string activity_selector {
            get {
                return ResourceManager.GetString("activity_selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selector used to find the element(s), supports mapping workflow variables by using {{variablename}} 的本地化字符串。
        /// </summary>
        public static string activity_selector_help {
            get {
                return ResourceManager.GetString("activity_selector_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Ctrl+C 的本地化字符串。
        /// </summary>
        public static string activity_sendctrlc {
            get {
                return ResourceManager.GetString("activity_sendctrlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Ctrl+C before trying to copy the Clipboard Content 的本地化字符串。
        /// </summary>
        public static string activity_sendctrlc_help {
            get {
                return ResourceManager.GetString("activity_sendctrlc_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string activity_showballontop_message {
            get {
                return ResourceManager.GetString("activity_showballontop_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message to show 的本地化字符串。
        /// </summary>
        public static string activity_showballontop_message_hint {
            get {
                return ResourceManager.GetString("activity_showballontop_message_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        public static string activity_showballontop_title {
            get {
                return ResourceManager.GetString("activity_showballontop_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title on bollanmessage 的本地化字符串。
        /// </summary>
        public static string activity_showballontop_title_hint {
            get {
                return ResourceManager.GetString("activity_showballontop_title_hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Balloon Tip 的本地化字符串。
        /// </summary>
        public static string activity_showballoontip {
            get {
                return ResourceManager.GetString("activity_showballoontip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show a small ballontip near the system tray, will respect OS message center settings 的本地化字符串。
        /// </summary>
        public static string activity_showballoontip_tooltip {
            get {
                return ResourceManager.GetString("activity_showballoontip_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String Result 的本地化字符串。
        /// </summary>
        public static string activity_stringresult {
            get {
                return ResourceManager.GetString("activity_stringresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return the result as a string 的本地化字符串。
        /// </summary>
        public static string activity_stringresult_help {
            get {
                return ResourceManager.GetString("activity_stringresult_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target 的本地化字符串。
        /// </summary>
        public static string activity_target {
            get {
                return ResourceManager.GetString("activity_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The target user or role 的本地化字符串。
        /// </summary>
        public static string activity_target_help {
            get {
                return ResourceManager.GetString("activity_target_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        public static string activity_text {
            get {
                return ResourceManager.GetString("activity_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        public static string activity_timeout {
            get {
                return ResourceManager.GetString("activity_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait this long before giving up and either failing or continuing depending on other settings 的本地化字符串。
        /// </summary>
        public static string activity_timeout_help {
            get {
                return ResourceManager.GetString("activity_timeout_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type Text 的本地化字符串。
        /// </summary>
        public static string activity_typetext {
            get {
                return ResourceManager.GetString("activity_typetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send keyboard strokes to what ever that has focus, should only be used by recorder 的本地化字符串。
        /// </summary>
        public static string activity_typetext_tooltip {
            get {
                return ResourceManager.GetString("activity_typetext_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Virtual Click 的本地化字符串。
        /// </summary>
        public static string activity_virtualclick {
            get {
                return ResourceManager.GetString("activity_virtualclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Try and do a Virtual click instead of using the mouse, not all elements supports this 的本地化字符串。
        /// </summary>
        public static string activity_virtualclick_help {
            get {
                return ResourceManager.GetString("activity_virtualclick_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait until Completed 的本地化字符串。
        /// </summary>
        public static string activity_waitforcompleted {
            get {
                return ResourceManager.GetString("activity_waitforcompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait for Completion before continuing with workflow 的本地化字符串。
        /// </summary>
        public static string activity_waitforcompleted_help {
            get {
                return ResourceManager.GetString("activity_waitforcompleted_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        public static string activity_width {
            get {
                return ResourceManager.GetString("activity_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If set, will move the window to this location 的本地化字符串。
        /// </summary>
        public static string activity_width_help {
            get {
                return ResourceManager.GetString("activity_width_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow 的本地化字符串。
        /// </summary>
        public static string activity_workflow {
            get {
                return ResourceManager.GetString("activity_workflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use this workflow 的本地化字符串。
        /// </summary>
        public static string activity_workflow_help {
            get {
                return ResourceManager.GetString("activity_workflow_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X 的本地化字符串。
        /// </summary>
        public static string activity_x {
            get {
                return ResourceManager.GetString("activity_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If set, will move the window to this location 的本地化字符串。
        /// </summary>
        public static string activity_x_help {
            get {
                return ResourceManager.GetString("activity_x_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y 的本地化字符串。
        /// </summary>
        public static string activity_y {
            get {
                return ResourceManager.GetString("activity_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If set, will move the window to this location 的本地化字符串。
        /// </summary>
        public static string activity_y_help {
            get {
                return ResourceManager.GetString("activity_y_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Animate Mouse 的本地化字符串。
        /// </summary>
        public static string animatemouse {
            get {
                return ResourceManager.GetString("animatemouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        public static string author {
            get {
                return ResourceManager.GetString("author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser addons 的本地化字符串。
        /// </summary>
        public static string browseraddons {
            get {
                return ResourceManager.GetString("browseraddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ok 的本地化字符串。
        /// </summary>
        public static string button_ok {
            get {
                return ResourceManager.GetString("button_ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel key 的本地化字符串。
        /// </summary>
        public static string cancelkey {
            get {
                return ResourceManager.GetString("cancelkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chrome 的本地化字符串。
        /// </summary>
        public static string chrome {
            get {
                return ResourceManager.GetString("chrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Click PostWait 的本地化字符串。
        /// </summary>
        public static string clickpostwait {
            get {
                return ResourceManager.GetString("clickpostwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy ID 的本地化字符串。
        /// </summary>
        public static string copyid {
            get {
                return ResourceManager.GetString("copyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Relative Filename 的本地化字符串。
        /// </summary>
        public static string copyrelativefilename {
            get {
                return ResourceManager.GetString("copyrelativefilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Debug 的本地化字符串。
        /// </summary>
        public static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment out 的本地化字符串。
        /// </summary>
        public static string designer_menu_commentout {
            get {
                return ResourceManager.GetString("designer_menu_commentout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run from here 的本地化字符串。
        /// </summary>
        public static string designer_menu_runfromhere {
            get {
                return ResourceManager.GetString("designer_menu_runfromhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run this activity 的本地化字符串。
        /// </summary>
        public static string designer_menu_runthis {
            get {
                return ResourceManager.GetString("designer_menu_runthis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uncomment 的本地化字符串。
        /// </summary>
        public static string designer_menu_uncomment {
            get {
                return ResourceManager.GetString("designer_menu_uncomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Detectors 的本地化字符串。
        /// </summary>
        public static string detectors {
            get {
                return ResourceManager.GetString("detectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable local caching 的本地化字符串。
        /// </summary>
        public static string disable_local_caching {
            get {
                return ResourceManager.GetString("disable_local_caching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        public static string dock_logging {
            get {
                return ResourceManager.GetString("dock_logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        public static string dock_output {
            get {
                return ResourceManager.GetString("dock_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        public static string dock_properties {
            get {
                return ResourceManager.GetString("dock_properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Snippets 的本地化字符串。
        /// </summary>
        public static string dock_snippets {
            get {
                return ResourceManager.GetString("dock_snippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbox 的本地化字符串。
        /// </summary>
        public static string dock_toolbox {
            get {
                return ResourceManager.GetString("dock_toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Workflow Instances 的本地化字符串。
        /// </summary>
        public static string dock_workflowinstances {
            get {
                return ResourceManager.GetString("dock_workflowinstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edge 的本地化字符串。
        /// </summary>
        public static string edge {
            get {
                return ResourceManager.GetString("edge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit Application 的本地化字符串。
        /// </summary>
        public static string exitapplication {
            get {
                return ResourceManager.GetString("exitapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Files 的本地化字符串。
        /// </summary>
        public static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Firefox 的本地化字符串。
        /// </summary>
        public static string firefox {
            get {
                return ResourceManager.GetString("firefox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string general {
            get {
                return ResourceManager.GetString("general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include Prerelease 的本地化字符串。
        /// </summary>
        public static string include_prerelease {
            get {
                return ResourceManager.GetString("include_prerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installed 的本地化字符串。
        /// </summary>
        public static string installed {
            get {
                return ResourceManager.GetString("installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logging 的本地化字符串。
        /// </summary>
        public static string logging {
            get {
                return ResourceManager.GetString("logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reload 的本地化字符串。
        /// </summary>
        public static string main_reload {
            get {
                return ResourceManager.GetString("main_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record directly into designer 的本地化字符串。
        /// </summary>
        public static string main_settings_recording_add_to_designer {
            get {
                return ResourceManager.GetString("main_settings_recording_add_to_designer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string mainnew {
            get {
                return ResourceManager.GetString("mainnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenRPA 的本地化字符串。
        /// </summary>
        public static string maintitle {
            get {
                return ResourceManager.GetString("maintitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Project 的本地化字符串。
        /// </summary>
        public static string newproject {
            get {
                return ResourceManager.GetString("newproject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Workflow 的本地化字符串。
        /// </summary>
        public static string newworkflow {
            get {
                return ResourceManager.GetString("newworkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NodeRED 的本地化字符串。
        /// </summary>
        public static string nodered {
            get {
                return ResourceManager.GetString("nodered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created at 的本地化字符串。
        /// </summary>
        public static string open_created {
            get {
                return ResourceManager.GetString("open_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Created by 的本地化字符串。
        /// </summary>
        public static string open_createdby {
            get {
                return ResourceManager.GetString("open_createdby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string open_edit {
            get {
                return ResourceManager.GetString("open_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit XAML 的本地化字符串。
        /// </summary>
        public static string open_edit_xaml {
            get {
                return ResourceManager.GetString("open_edit_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last modified at 的本地化字符串。
        /// </summary>
        public static string open_modified {
            get {
                return ResourceManager.GetString("open_modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last modified by 的本地化字符串。
        /// </summary>
        public static string open_modifiedby {
            get {
                return ResourceManager.GetString("open_modifiedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string open_name {
            get {
                return ResourceManager.GetString("open_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Package Manager 的本地化字符串。
        /// </summary>
        public static string open_package_manager {
            get {
                return ResourceManager.GetString("open_package_manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serializable 的本地化字符串。
        /// </summary>
        public static string open_serializable {
            get {
                return ResourceManager.GetString("open_serializable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 State 的本地化字符串。
        /// </summary>
        public static string open_state {
            get {
                return ResourceManager.GetString("open_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFlow 的本地化字符串。
        /// </summary>
        public static string openflow {
            get {
                return ResourceManager.GetString("openflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenRPA 的本地化字符串。
        /// </summary>
        public static string openrpa {
            get {
                return ResourceManager.GetString("openrpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Packages 的本地化字符串。
        /// </summary>
        public static string packages {
            get {
                return ResourceManager.GetString("packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permissions 的本地化字符串。
        /// </summary>
        public static string permissions {
            get {
                return ResourceManager.GetString("permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string permissions_delete {
            get {
                return ResourceManager.GetString("permissions_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoke 的本地化字符串。
        /// </summary>
        public static string permissions_invoke {
            get {
                return ResourceManager.GetString("permissions_invoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read 的本地化字符串。
        /// </summary>
        public static string permissions_read {
            get {
                return ResourceManager.GetString("permissions_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string permissions_update {
            get {
                return ResourceManager.GetString("permissions_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string permissionswindow_delete {
            get {
                return ResourceManager.GetString("permissionswindow_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New 的本地化字符串。
        /// </summary>
        public static string permissionswindow_new {
            get {
                return ResourceManager.GetString("permissionswindow_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Play 的本地化字符串。
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugins 的本地化字符串。
        /// </summary>
        public static string plugins {
            get {
                return ResourceManager.GetString("plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record 的本地化字符串。
        /// </summary>
        public static string record {
            get {
                return ResourceManager.GetString("record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recorder plugins 的本地化字符串。
        /// </summary>
        public static string recorderplugins {
            get {
                return ResourceManager.GetString("recorderplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording Overlay 的本地化字符串。
        /// </summary>
        public static string recordingoverlay {
            get {
                return ResourceManager.GetString("recordingoverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename 的本地化字符串。
        /// </summary>
        public static string rename {
            get {
                return ResourceManager.GetString("rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string ribbon_search {
            get {
                return ResourceManager.GetString("ribbon_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run plugins 的本地化字符串。
        /// </summary>
        public static string runplugins {
            get {
                return ResourceManager.GetString("runplugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runtime 的本地化字符串。
        /// </summary>
        public static string runtime {
            get {
                return ResourceManager.GetString("runtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector 的本地化字符串。
        /// </summary>
        public static string selector {
            get {
                return ResourceManager.GetString("selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector Verbose 的本地化字符串。
        /// </summary>
        public static string selectorverbose {
            get {
                return ResourceManager.GetString("selectorverbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings File 的本地化字符串。
        /// </summary>
        public static string settingsfile {
            get {
                return ResourceManager.GetString("settingsfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Signout 的本地化字符串。
        /// </summary>
        public static string signout {
            get {
                return ResourceManager.GetString("signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow Motion 的本地化字符串。
        /// </summary>
        public static string slowmotion {
            get {
                return ResourceManager.GetString("slowmotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        public static string status_disconnected {
            get {
                return ResourceManager.GetString("status_disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tesseract 的本地化字符串。
        /// </summary>
        public static string tesseract {
            get {
                return ResourceManager.GetString("tesseract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tools 的本地化字符串。
        /// </summary>
        public static string tools {
            get {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Type 的本地化字符串。
        /// </summary>
        public static string tools_change_type {
            get {
                return ResourceManager.GetString("tools_change_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap Animate 的本地化字符串。
        /// </summary>
        public static string tools_swap_animate {
            get {
                return ResourceManager.GetString("tools_swap_animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap SendKeys 的本地化字符串。
        /// </summary>
        public static string tools_swap_sendkeys {
            get {
                return ResourceManager.GetString("tools_swap_sendkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Swap Virtual Clicking 的本地化字符串。
        /// </summary>
        public static string tools_swap_virtualclick {
            get {
                return ResourceManager.GetString("tools_swap_virtualclick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Language 的本地化字符串。
        /// </summary>
        public static string uilanguage {
            get {
                return ResourceManager.GetString("uilanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        public static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use SendKeys 的本地化字符串。
        /// </summary>
        public static string usesendkeys {
            get {
                return ResourceManager.GetString("usesendkeys", resourceCulture);
            }
        }
    

        /// <summary>
        ///   查找类似 Use Virtual Clicks 的本地化字符串。
        /// </summary>
        public static string usevirtualclicks {
            get {
                return ResourceManager.GetString("usevirtualclicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        public static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verbose 的本地化字符串。
        /// </summary>
        public static string verbose {
            get {
                return ResourceManager.GetString("verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visual Tracking 的本地化字符串。
        /// </summary>
        public static string visualtracking {
            get {
                return ResourceManager.GetString("visualtracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }

    }
}
